version: '3'

services:
  demo_nginx:
    image: nginx:latest
    container_name: demo-nginx
    volumes:
      - .:/var/www/demo/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "9876:80"
    links:
      - demo_php_fpm

  demo_php_fpm:
    build:
      context: ./docker
      dockerfile: ./php-fpm/Dockerfile
    container_name: demo-php
    working_dir: /var/www/demo/
    volumes:
      - .:/var/www/demo/
    environment:
      XDEBUG_REMOTE_HOST: host.docker.internal
      PHP_IDE_CONFIG: serverName=Docker
